config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  resources :docs
  get 'search' => 'home#search', as: :search

  namespace :admin do
    #get '/' => 'home#index'
    root to: 'home#index'
    get 'make-index' => 'home#make_index'
    get 'crawl-geektimes' => 'home#crawl_geektimes'
    get 'zip-index' => 'home#zip_index'
    get 'ranging' => 'home#ranging'
    get 'evaluation-search' => 'home#evaluation_search'
    get 'clustering-docs' => 'home#clustering_docs'
    get 'logout' => 'home#logout'
  end
end

app/models/doc.rb
require 'digest'

class Doc
  include ActiveModel::Model

  attr_accessor :id, :url, :title, :content
  validates_presence_of :url, :content

  FOLDER = "#{Rails.root}/data/docs"

  def initialize(id:nil, url:nil, title:nil, content:nil)
    @id = id
    @url = url
    @title = title
    @content = content

    @is_lazy_readed = false
    @is_readed = false
  end

  def save
    if valid?
      @id = Digest::MD5.hexdigest(@url)
      @id += ".txt"
      File.open("#{FOLDER}/#{@id}", 'w:UTF-8') do |f|
        f.write(@url)
        f.write("\n")
        f.write(@title)
        f.write("\n\n")
        f.write(@content)
      end
    else
      #raise Exception.new("doc not valid")
    end
  end

  def read
    if @id == nil
      raise Exception.new("can't read file (id not initialize)")
    end
    if @is_readed
      return self
    end
    File.open("#{FOLDER}/#{@id}", 'r:UTF-8') do |f|
      @url = f.readline.chomp
      @title = f.readline.chomp
      f.readline
      @content = f.read
    end
    @is_readed = true
    @is_lazy_readed = true
    self
  end

  def lazy_read
    # read only title and url
    if @id == nil
      raise Exception.new("can't read file (id not initialize)")
    end
    if @is_lazy_readed
      return self
    end
    File.open("#{FOLDER}/#{@id}", 'r:UTF-8') do |f|
      @url = f.readline.chomp
      @title = f.readline.chomp
    end
    @is_lazy_readed = true
    self
  end

  def exists?
    File.exists?("#{FOLDER}/#{@id}")
  end

  def delete
    if @id == nil
      raise Exception.new("can't read file (id not initialize)")
    end
    File.delete("#{FOLDER}/#{@id}")
  end

  def [](key)
    case key
    when :id
      @id.sub('.txt', '')
    when :title
      @title
    when :content
      @content
    else
      nil
    end
  end

  def inspect
    "#<Doc @id=#{@id}>"
  end

  def self.all
    dir = Dir.new(FOLDER)
    files = dir.select { |file_name| file_name =~ /\A[A-z0-9]+\.txt\z/ }
    dir.close
    files.map { |file_name| self.new(id:file_name) }
  end
  def self.find(id:)
    id = "#{id}.txt" unless id.end_with?('.txt')
    self.all.detect { |d| d.id == id }
  end
  def self.count
    dir = Dir.new(FOLDER)
    files = dir.select { |file_name| file_name =~ /\A[A-z0-9]+\.txt\z/ }
    dir.close
    files.count
  end
end

app/models/setting.rb
require "yaml"

class Setting
  FILENAME = "#{Rails.root}/data/settings.yml"

  def initialize
    File.open(FILENAME, 'r:UTF-8') do |f|
      @data = YAML.load(f) || {}
    end
  end

  def added_text?
    @data[:added_text] ||= false
  end
  def added_text=(added_text)
    @data[:added_text] = added_text
  end
  def added_text!
    @data[:added_text] = true
  end

  def save
    File.open(FILENAME, 'w:UTF-8') do |f|
      f.write(@data.to_yaml)
    end
  end
end

app/controllers/admin/home_controller.rb
require "#{Rails.root}/lib/tasks/geektimes_crawler"

class Admin::HomeController < ApplicationController
  http_basic_authenticate_with name: "artem", password: "admin"

  def index
  end
  def make_index
    start_time = Time.now
    TextProcessing::DocIndexBuilder.build_all
    TextProcessing::MainIndexBuilder.build
    render inline: "<p>Индекс построен успешно за #{Time.now - start_time} секунд</p>"
  end
  # https://ru.wikipedia.org/wiki/TF-IDF
  # def zip_index
  #   render inline: "<p>zip_index</p>"
  # end
  # def ranging
  #   render inline: "<p>ranging</p>"
  # end
  # def evaluation_search
  #   render inline: "<p>evaluation_search</p>"
  # end
  # def clustering_docs
  #   render inline: "<p>clustering_docs</p>"
  # end
  def crawl_geektimes
    start_time = Time.now
    ::GeektimesCrawler.new(1).crawl
    render inline: "<p>Загрузка документов выполнена успешно за #{Time.now - start_time} секунд</p>"
  end
  def logout
    redirect_to :root
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  around_action :set_settings

  def set_settings
    #@setting = Setting.new
    yield
    #@setting.save
  end
end

app/controllers/docs_controller.rb
class DocsController < ApplicationController
  http_basic_authenticate_with name: "artem", password: "admin",  only: [:create, :destroy]

  def index
    @docs = Doc.all
    @docs = Kaminari.paginate_array(@docs).page(params[:page]).per(20)
    @docs.each(&:lazy_read)
  end
  def show
    @doc = Doc.find(id: params[:id])
    @doc.try(:read)

    if params[:highlight]
      user_input = params[:q] || ""
      search_engine = TextProcessing::SearchEngine.new
      positions = search_engine.search_position(user_input, @doc[:id])

      content = @doc.content

      pos = []
      positions.each do |position|
        pos += position[1]
      end

      _START_TAG = '<b style="background: yellow">'.freeze
      _END_TAG = '</b>'.freeze
      _COUNT_START_TAG = _START_TAG.length
      _STEP_OFFSET = _COUNT_START_TAG + _END_TAG.length

      offset = 0
      pos.sort.each do |start_pos|
        content = content.insert(start_pos + offset, _START_TAG) # <b>
        end_pos = content.index(/[^а-яё]/i, start_pos + offset + _COUNT_START_TAG) # 3
        content = content.insert(end_pos || -1, _END_TAG) #</b>
        offset += _STEP_OFFSET # 7
      end

      @doc.content = content
    end

    # respond_to do |format|
    #   format.txt { render 'show.html.erb' }
    # end
  end
  def new
    @doc = Doc.new
  end
  def create
    @doc = Doc.new(**doc_params.to_hash.symbolize_keys)
    if @doc.valid?
      @doc.save
      redirect_to action: :show, id: @doc[:id]
    else
      render :new
    end
  end
  def edit
    @doc = Doc.find(id: params[:id])
    @doc.try(:read)
  end
  def destroy
    @doc = Doc.find(id: params[:id])
    @doc.try(:delete)
    redirect_to action: :index
  end

  private
  def doc_params
    params.require(:doc).permit(:title, :url, :content)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def search
    search_engine = TextProcessing::SearchEngine.new
    @docs = search_engine.search(params[:q])

    @count = @docs.count
    @all_count = Doc.count
    @search_time = search_engine.search_time

    @docs = Kaminari.paginate_array(@docs).page(params[:page]).per(50)
    @docs.each(&:lazy_read)
  end
end

app/helpers/admin/home_helper.rb
module Admin::HomeHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/admin/home/index.html.erb
<h1>Административная панель</h1>

<%= button_to "Построение индекса", { action: "make_index" }, method: :get, class: "class_html", id: "id_html" %>
<%= button_to "Загрузить документы", { action: "crawl_geektimes" }, method: :get, class: "class_html", id: "id_html" %>
<%#= button_to "Сжатие индекса", { action: "zip_index" }, method: :get %>
<%#= button_to "Ранжирование", { action: "ranging" }, method: :get %>
<%#= button_to "Оценка информационного поиска", { action: "evaluation_search" }, method: :get %>
<%#= button_to "Кластеризация документов", { action: "clustering_docs" }, method: :get %>
<%= button_to "На главную страницу", { action: "logout" }, method: :get %>

app/views/docs/_docs.html.erb
<% @docs.each do |doc| %>
  <h3> <%= link_to doc.title, doc_path(doc[:id], highlight: locals[:highlight], q: locals[:q]) %> </h3>
  <span><%= link_to "Редактировать", edit_doc_path(doc[:id]) %></span>
  <span><%= link_to "Удалить", doc_path(doc[:id]), method: :delete %></span>
  <div style="margin-bottom: 20px">___________________________________</div>
<% end %>

app/views/docs/_form.html.erb
<%= form_for(@doc) do |f| %>
  <%= f.label :title %> </br>
  <%= f.text_field :title, style: "width: 850px;" %> </br>
  <%= f.label :url %> </br>
  <%= f.text_field :url, style: "width: 850px;" %> </br>
  <%= f.label :content %> </br>
  <%= f.text_area :content, style: "height: 400px; width: 900px;" %> </br>

  <%= f.submit "Сохранить" %>
<% end %>

app/views/docs/edit.html.erb
<h1>Редактировать документ</h1>
<%= render 'form' %>

app/views/docs/index.html.erb
<h1>Документы</h1>

<h5><%= link_to "Создать новый документ", new_doc_path %></h5>

<%= render 'docs', locals: {} %>

<%= paginate @docs %>

app/views/docs/new.html.erb
<h1>Создать новый документ</h1>
<%= render 'form' %>

app/views/docs/show.html.erb
<h1><%= @doc.title %></h1>
<h5><a href=<%= @doc.url %>> <%=@doc.url %></a></h5>

<article>
  <%= @doc.content.gsub("\n", "</br>").html_safe %>
</article>
<span><%= link_to "Редактировать", edit_doc_path(@doc[:id]) %></span>
<span><%= link_to "Удалить", doc_path(@doc[:id]), method: :delete %></span>

app/views/home/index.html.erb
<h1>SearchApp</h1>
<p>
  <%= form_tag search_path, method: :get do %>
  <%= text_field_tag :q %>
  <%= submit_tag "Найти", name: nil %>
  <% end %>
</p>

<%= link_to "Просмотр всех документов", docs_path %>

<%= link_to "Войти в административную панель", admin_root_path, style: "position: fixed; left: 0; bottom: 0" %>

app/views/home/search.html.erb
<h1>Найденные документы</h1>
<%= link_to 'Вернуться на главную', root_path %>

<% if @count > 0 %>
  <h3>Найдено <%= @count %> из <%= @all_count %> по запросу: "<%= params[:q] %>"</h3>
<% else %>
  <h3>К сожалению по запросу: "<%= params[:q] %>" ничего не найдно</h3>
<% end %>

<h3>Время поиска: <%= @search_time %> секунд</h3>

<%= render 'docs/docs', locals: {highlight: 1, q: params[:q]} %>

<%= paginate @docs %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Searchapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>